brioche-dev/brioche

Cargo.lock
Cargo.toml
crates/brioche-pack/Cargo.toml
crates/brioche-pack/src/encoding.rs
crates/brioche-pack/src/lib.rs
crates/brioche-packed-exec/Cargo.toml
crates/brioche-packed-exec/src/main.rs
crates/brioche-packed-userland-exec/Cargo.toml
crates/brioche-packed-userland-exec/src/main.rs

This PR decreases the file sizes of the `brioche-packed-exec` and `brioche-packed-userland-exec` packed binary wrappers. Based on some recent CI runs ([CI #16](https://github.com/brioche-dev/brioche/actions/runs/7384610242/job/20087850566), [CI #17](https://github.com/brioche-dev/brioche/actions/runs/7384714590/job/20088109401)), the new binary sizes are now:
- `brioche-packed-userland-exec`: 150KB → 86KB
- `brioche-packed-exec`: 130K → 78K
Most of the changes I made were inspired by tips from the [min-sized-rust](https://github.com/johnthagen/min-sized-rust) repo. Several changes were just compiler options that already landed in `main`, but this PR includes the spicier ones. To summarize the changes:
- Avoid `format!` as much as possible
- There is still some use of `format!` in …

Optimize file sizes of `brioche-packed-exec` and `brioche-packed-userland-exec`

---

crates/brioche/src/brioche/project.rs
crates/brioche/src/brioche/project/analyze.rs
crates/brioche/src/brioche/script.rs
crates/brioche/src/brioche/script/check.rs
crates/brioche/src/brioche/script/compiler_host.rs
crates/brioche/src/brioche/script/lsp.rs
crates/brioche/src/brioche/script/specifier.rs
crates/brioche/src/fs_utils.rs
crates/brioche/src/main.rs
crates/brioche/tests/script_project_analyze.rs
crates/brioche/tests/script_specifiers.rs

This PR overhauls the "project analysis" phase to find all imported file paths ahead-of-time. This doesn't have much impact on functionality, but it will be important for things like "format all files in this project".
One outcome of this PR that is an improvement though: the TypeScript Language Service Host no longer does blocking I/O to read files! 🎉 This is because we now asynchronously load documents into the `BriocheCompilerHost` type before calling into the TypeScript code. Then, the TypeScript code uses Deno ops that just read from `BriocheCompilerHost`, and assume that the documents have already been loaded asynchronously.
There are still some instances of blocking I/O-- namely when resolving import specifiers-- but it'll take some more work to fix those cases.

Improve project analysis

---

crates/brioche/src/brioche/artifact.rs
crates/brioche/src/brioche/resolve.rs

This PR replaces the `remove` artifact with `insert`. "Removal" is now handled by inserting a value of `null`, meaning this new `insert` artifact is strictly more general.

Replace `remove` lazy artifact with `insert`

---

crates/brioche/src/main.rs
crates/brioche/src/reporter.rs

This PR adds a summary line during builds, showing the total elapsed time as well as the total number of in-progress / complete jobs:
A final summary is also shown once a build completes (this will be printed even when not using the fancier SuperConsole output).

Show summary line during build

---

Cargo.lock
crates/brioche/Cargo.toml
crates/brioche/benches/brioche_bench/mod.rs
crates/brioche/benches/resolve.rs
crates/brioche/src/brioche/artifact.rs
crates/brioche/src/brioche/blob.rs
crates/brioche/src/brioche/input.rs
crates/brioche/src/brioche/output.rs
crates/brioche/src/brioche/resolve.rs
crates/brioche/src/brioche/resolve/download.rs
crates/brioche/src/brioche/resolve/unpack.rs
crates/brioche/tests/artifact_hash_stable.rs
crates/brioche/tests/brioche_test/mod.rs
crates/brioche/tests/input.rs
crates/brioche/tests/output.rs
crates/brioche/tests/resolve_basic.rs
crates/brioche/tests/resolve_cache.rs
crates/brioche/tests/resolve_process.rs
crates/brioche/tests/resolve_proxy.rs
crates/brioche/tests/script_eval.rs

This PR updates how `Directory` artifacts are represented: rather than storing a map of file/entry names, it now stores a blob ID (much like a file artifact does). The blob referred to by this ID will then contain a (canonicalized) JSON payload that can be deserialized into a `DirectoryListing` structure (which in turn, contains a map of file/entry names).
This new representation was inspired by Git's representation of directories, which internally use "directory tree objects", or plain text files listing the other objects making up the directory's entries (I found the ["inside .git"](https://wizardzines.com/comics/inside-git/) zine especially helpful for understanding this!)
I was hoping this new implementation would be noticeably faster. While testing did show some improvements in some …

Update `Directory` artifacts to use blobs

---

Cargo.lock
crates/brioche-pack/Cargo.toml
crates/brioche-pack/src/encoding.rs
crates/brioche-pack/src/lib.rs
crates/brioche/Cargo.toml
crates/brioche/src/brioche/artifact.rs
crates/brioche/src/brioche/script.rs
crates/brioche/src/brioche/script/js.rs
crates/brioche/src/encoding.rs
crates/brioche/src/sandbox.rs
crates/brioche/tests/artifact_hash_stable.rs

This PR replaces all uses of URL encoding in Brioche (a.k.a percent encoding) with [`tick-encoding`](https://crates.io/crates/tick-encoding) (a small crate I wrote over the weekend). While URL encoding has worked well, it has some undesirable properties in the context of Brioche:
- No unambiguous canonical encoding (e.g. `encodeURI` vs `encodeURIComponents` both being valid URL encodings). This is bad in the context of hashing artifacts, where it's better to ideally have one unambiguous serialized representation of an artifact
- More wasteful than it has to be. Since we're not bound by the limitations of URLs, we end up needing to escape some characters that absolutely do not need to be escaped in JSON. As such, we just end up wasting a bit of space.
- Kinda ugly. Trying to read a …

Use "tick encoding" for encoding binary data in JSON

---

crates/brioche/src/brioche/input.rs
crates/brioche/src/brioche/output.rs
crates/brioche/src/brioche/resolve/process.rs
crates/brioche/src/fs_utils.rs
crates/brioche/src/main.rs
crates/brioche/tests/output.rs
crates/brioche/tests/resolve_process.rs

This PR updates the files under `~/.local/share/brioche/locals` to use hardlinks where possible, which saves a massive amount of disk space. When building [`std`](https://github.com/brioche-dev/brioche-packages/tree/db84686c46eb364ca0f32fd46107b5a800da535d/std) with `brioche build ./std -e native`, this seems to cut the total disk usage down from ~18 GB to ~8 GB!
We use hardlinks in the following cases:
- A local read-only `File` artifact gets hardlinked to its "content blob" (from `~/.local/share/brioche/blobs`)
- A local `File` artifact that has `resources` gets hardlinked to a version without its resources
- A local `Directory` artifact will contain hardlinks to all the files contained within it
This means we greatly cut down on data duplication. Now, we should only be duplicating data …

Optimize locals with hardlinks

---

Cargo.lock
crates/brioche/Cargo.toml
crates/brioche/src/brioche/artifact.rs

This PR builds on #9, but replaces the [`olpc-cjson`](https://crates.io/crates/olpc-cjson) crate (which implements the [OLPC Canonical JSON spec](https://wiki.laptop.org/go/Canonical_JSON)) with the [`json-canon`](https://crates.io/crates/json-canon) crate (which implements the [IETF JSON Canonicalization Scheme](https://datatracker.ietf.org/doc/html/rfc8785) (JCS)).
The reason for the switch is that the OLPC Canonical JSON representation is _not_ a valid subset of JSON in many cases. JCS is on the other hand, so after serializing JSON as JCS, you can then deserialize it with a normal JSON parser.

Swap `olpc-cjson` with `json-canon`

---

crates/brioche/src/brioche/artifact.rs
crates/brioche/src/brioche/resolve.rs
crates/brioche/src/brioche/script.rs
crates/brioche/tests/resolve_process.rs
crates/brioche/tests/resolve_proxy.rs

This PR updates how `Proxy` artifacts work. Previously, they were always stored only as in-memory values, meaning that it wasn't easy to get the data that a proxy was wrapping. Now, they are just represented as normal blob values, meaning there's an easy and consistent way to look them up. I believe this will help simplify work with persisting / syncing artifacts over the network in the future.
One disadvantage is that this PR hurts performance: running `brioche build ./std -e native` in the [`brioche-packages`](https://github.com/brioche-dev/brioche-packages/tree/db84686c46eb364ca0f32fd46107b5a800da535d) repo went up from 400ms to 500ms for a fully-cached build. I believe we'll be able to win back some of this performance in the future.

Store proxy artifacts as blobs

---

crates/brioche/src/brioche/artifact.rs
crates/brioche/src/brioche/resolve/process.rs
crates/brioche/tests/artifact_hash_stable.rs
crates/brioche/tests/resolve_process.rs

This PR adds a new `outputScaffold` field to the `Process` artifact, which is optional and can be set to any type of `LazyArtifact` value. When set, the process will start with `$BRIOCHE_OUTPUT` (the output path) pre-populated with the specified artifact.
In the simplest case, this is a minor convenience improvement: rather than copying an artifact into `$BRIOCHE_OUTPUT` to modify it, or having to do something like `mkdir -p "$BRIOCHE_OUTPUT/bin"` or similar, the process can now be set to the existing artifact to copy in, or you can set it to a basic directory structure like this:
```typescript
std.process({
// ...
// Create the folder "$BRIOCHE_OUTPUT/bin" when the process starts
outputScaffold: std.directory({
bin: std.directory()
}),
});
```
A better use-case is that this makes it …

Add `Process.outputScaffold`

---

Cargo.lock
crates/brioche/Cargo.toml
crates/brioche/src/brioche/artifact.rs
crates/brioche/src/brioche/resolve/unpack.rs

This PR makes two minor changes to resolving the "unpack" lazy artifact:
- Ignore `XHeader` and `XGlobalHeader` tar entires. I believe these entries both specify extra file metadata, but Brioche artifacts can't store this metadata anyway so skipping should be totally safe.
- Add support for unpacking bzip2-compressed tar archives.

Minor improvements to using `unpack` with tarfiles

---

crates/brioche/src/brioche/blob.rs
crates/brioche/src/brioche/output.rs
crates/brioche/src/brioche/resolve/process.rs
crates/brioche/src/fs_utils.rs
crates/brioche/src/main.rs
crates/brioche/tests/output.rs

This PR makes it so files written to `~/.local/share/brioche/locals` and `~/.local/share/brioche/blobs` have their modified time (mtime) set to the timestamp 2000-01-01 00:00:00 UTC.
Nix uses the timestamp 1970-01-01 00:00:00 UTC instead (the Unix epoch), but I chose to use a more recent timestamp, as at least ZIP files have problems with timestamps before 1980. The choice of the year 2000 is arbitrary, but I wanted to avoid issues with ZIP files at least.

Set file modified times for locals and blobs

---

Cargo.lock
crates/brioche/Cargo.toml
crates/brioche/src/brioche.rs
crates/brioche/src/brioche/project.rs
crates/brioche/src/brioche/project/analyze.rs
crates/brioche/src/brioche/script.rs
crates/brioche/src/brioche/script/check.rs
crates/brioche/src/brioche/script/compiler_host.rs
crates/brioche/src/brioche/script/evaluate.rs
crates/brioche/src/brioche/script/format.rs
crates/brioche/src/brioche/script/lsp.rs
crates/brioche/src/brioche/script/specifier.rs
crates/brioche/src/brioche/vfs.rs
crates/brioche/src/fs_utils.rs
crates/brioche/src/main.rs
crates/brioche/tests/brioche_test/mod.rs
crates/brioche/tests/project_hash.rs
crates/brioche/tests/script_check.rs
crates/brioche/tests/script_eval.rs
crates/brioche/tests/script_project_analyze.rs
crates/brioche/tests/script_project_resolve.rs
crates/brioche/tests/script_specifiers.rs

This PR refactors how modules are loaded. The key is 2 new types:
- `Vfs` (virtual filesystem): Supports loading and caching files from disk, or synchronously getting the cached contents of a previously-loaded file. A VFS can be constructed using either `Vfs::immutable()` and `Vfs::mutable()`
- `Vfs::immutable()`: Captures an immutable snapshot of files, then derives a file ID based on a hash of the file contents
- `Vfs::mutable()`: Captures a mutable snapshot of files, then assigns a random ULID as the ID. Used for the LSP specifically, where we need to update an in-memory snapshot of files
- `Projects`: A set of projects loaded in memory. When a project is loaded, it returns a `ProjectHash`, which can be used to look up project-specific information
With these changes, `Project` itself …

Refactor module resolution with new `Projects` and `Vfs` types

---

Cargo.lock
crates/brioche/Cargo.toml
crates/brioche/benches/brioche_bench/mod.rs
crates/brioche/src/lib.rs
crates/brioche/src/main.rs
crates/brioche/src/project.rs
crates/brioche/src/registry.rs
crates/brioche/tests/brioche_test/mod.rs
crates/brioche/tests/project_load.rs
crates/brioche/tests/registry_client.rs
crates/brioche/tests/script_check.rs
crates/brioche/tests/script_eval.rs
crates/brioche/tests/script_specifiers.rs

This PR adds initial support for resolving projects from a registry. When a Brioche project includes a dependency like this:
```ts
export const project = {
dependencies: {
std: "*",
},
};
```
...we now fetch the project named `std` (and tagged `latest`) from the registry API. The registry API can be configured with the key `registry_url` in `~/.config/brioche/config.toml`, which should point to a hosted instance of [brioche-registry](https://github.com/brioche-dev/brioche-registry) (the default value is currently `http://localhost:2000`-- the default development port-- since there isn't a publicly hosted instance yet).
There isn't a command to upload to the registry at the moment, so projects can be published like this:
```bash
brioche export-project -p ./projects/std \
| curl -X POST …
```

Implement initial support for project registry

---

crates/brioche/src/bake.rs
crates/brioche/src/lib.rs
crates/brioche/src/main.rs
crates/brioche/src/registry.rs
crates/brioche/src/sync.rs

This PR implements a few minor changes to the syncing process to (hopefully) make it less painful to have large, long-running builds e.g. in CI/CD pipelines:
- Use [`reqwest-retry`](https://crates.io/crates/reqwest-retry) to automatically retry requests for all registry endpoints
- Tweak `reqwest-retry` settings for download recipes
- Update `--sync` to spawn a task to start syncing recipes mid-build. This makes it so, even if a build fails, hopefully at least some bakes should be synced to the registry. This would make a second run of the build hopefully able to pull already-cached versions of the parts of the build that succeeded.

Improve syncing consistency with retries and partial syncing

---

rust-toolchain.toml

This PR updates the `rust-toolchain.toml` file to lock the Rust toolchain to v1.77.x, the last version that was passing on `main`. Due to some unsoundness on the version of `deno_core` we're currently using, the upgrade to 1.78.0 broke the build. Pinning to v1.77 is a temporary fix until we update `deno_core` (which has already fixed the unsoundness upstream).

Pin Rust toolchain to 1.77

---

.github/workflows/ci.yml
Cargo.lock
crates/brioche-packed-userland-exec/Cargo.toml
crates/brioche-packed-userland-exec/src/linux.rs
crates/brioche-packed-userland-exec/src/main.rs
crates/brioche/Cargo.toml
crates/brioche/src/input.rs
crates/brioche/src/platform.rs
crates/brioche/src/sandbox.rs
crates/brioche/src/sandbox/linux.rs
crates/brioche/tests/bake_process.rs
crates/brioche/tests/brioche_test/mod.rs

`process` recipes have a `platform` field describing which platform they should bake on. Currently, the only variant for this field is `x86_64-linux`, meaning you can really only bake process recipes if you're already running on x86-64 Linux. That's not changing today, but there is a lot of code that's x86-64 Linux-specific, and that code causes builds to fail when trying to build on other platforms.
This PR adds `#[cfg]` attributes and uses the Cargo `targets.cfg(...)` feature so the build succeeds on other platforms. While you still won't be able to do a lot of things on other platforms, you can still interact with the registry, meaning you could still download Linux-specific artifacts that have already been baked and synced. You can also run the LSP or run `brioche check`.

Ensure Brioche can minimally run on platforms other than x86-64 Linux

---

crates/brioche/src/bake.rs
crates/brioche/src/bake/process.rs
crates/brioche/src/bake/unarchive.rs
crates/brioche/src/recipe.rs
crates/brioche/src/references.rs
crates/brioche/src/reporter.rs
crates/brioche/tests/bake_process.rs

This PR renames the `unpack` recipe type to `unarchive`, and all related functions, variables, etc. I made this change because we already use the term "packed executable", and I was worried that the two uses of the term could be easily confused

Rename `unpack` recipe to `unarchive`

---

crates/brioche/src/project.rs
crates/brioche/src/project/analyze.rs
crates/brioche/tests/project_load.rs

This PR relaxes the requirement that every `project.bri` file needs to include an explicit project definition (`export const project = { /* ... */ };`). Now, omitting the project definition will be equivalent to having a project definition of `{}`.
At the moment, this is fairly useless because nearly every project will still need to include a project definition to import dependencies, including `std`. This should change fairly quickly: you will soon also be able to include dependencies implicitly via `import` statements (instead of including each one in the project definition explicitly).

Make project definition optional in `project.bri`

---

crates/brioche/src/project.rs
crates/brioche/tests/brioche_test/mod.rs
crates/brioche/tests/project_load.rs
crates/brioche/tests/script_check.rs

This PR updates `.bri` modules so that dependencies can be added by just adding an `import` statement without first adding an equivalent entry in the `dependencies` field of the project definition. This means these two projects are now effectively equivalent:
```ts
// project1/project.bri
// Explicit dependency from the project definition
import * as std from "std";
export const project = {
dependencies: {
"std": "*",
},
};
```
```ts
// project2/project.bri
// Implicit dependency
import * as std from "std";
```
More specifically, if a project includes an import from another project (i.e. an import not starting with `./` or `/`), we check for the imported project in the `dependencies` field of the project definition. If it's not found, resolve it from the registry or workspace with the …

Implement implicit dependencies based on imports

---

crates/brioche/src/main.rs

This PR adds a new `brioche run` subcommand. It takes `-p` and `-e` args just like `brioche build` to specify the project/export to build, then runs the command from the output artifacts specified by the `-c` arg (defaults to `brioche-run`).
Here's a minimal example:
```ts
// example/project.bri
import * as std from "std";
export default function (): std.Recipe {
return std
.tools()
.insert("brioche-run", std.symlink({ target: "./bin/bash" }));
}
```
Running `brioche run -p example` will then run Bash.

Add `brioche run` subcommand

---

crates/brioche/src/bake/process.rs
crates/brioche/src/lib.rs
crates/brioche/src/recipe.rs
crates/brioche/src/references.rs
crates/brioche/src/sandbox.rs
crates/brioche/src/sandbox/linux.rs
crates/brioche/src/utils.rs
crates/brioche/tests/bake_process.rs
crates/brioche/tests/recipe_hash_stable.rs

Companion PR: brioche-dev/brioche-packages#6
This PR adds a way to enable networking for processes. This can be done by setting both the `unsafe` and `networking` options to true:
```ts
std.process({
command: std.tpl`${std.tools()}/bin/bash`,
args: ["-c", 'wget https://example.com -O "$BRIOCHE_OUTPUT"'],
env: {
// ...
},
unsafe: true,
networking: true,
});
```
When enabled, the sandbox will run the new process in the host's networking namespace to allow IP connections, and will also copy the host's `/etc/resolv.conf` file into the guest to support proper DNS resolution.
The idea behind `unsafe` is that enabling networking breaks the idea of "hermetic builds", since it depends on an external source. `unsafe` indicates extra care needs to be taken when using this feature, such as by using …

Implement process networking

---

crates/brioche/src/project.rs
crates/brioche/src/project/analyze.rs
crates/brioche/src/script.rs
crates/brioche/src/script/evaluate.rs
crates/brioche/tests/project_load.rs
crates/brioche/tests/script_eval.rs
crates/brioche/tests/script_project_analyze.rs

This PR implements support for `Brioche.get`, which creates a recipe by reading a file or directory from the current project. Or, more specifically, it makes three changes needed to implement this function:
1. Update project analysis to find invocations of `Brioche.get("...")` and add them to the module analysis. This is called a "static", because it's a special invocation that's recognized and parsed statically (trying to call it with a non-string literal will fail). There will be other kinds of statics besides `Brioche.get` in the future.
2. Update project loader to load statics: in this case, we use `create_input` to create an artifact from the file path, then add the artifact hash to the `Project` type
3. Add new `op_brioche_get_static` Deno op. It takes a module URL and a JSON …

Implement support for global `Brioche.get(...)` function

---

crates/brioche/src/project.rs
crates/brioche/src/project/analyze.rs
crates/brioche/src/script.rs
crates/brioche/tests/project_load.rs
crates/brioche/tests/script_eval.rs
crates/brioche/tests/script_project_analyze.rs

This PR follows up on #34, replacing the `Brioche.get(...)` function two functions instead: `Brioche.includeFile` and `Brioche.includeDirectory`. I wasn't really happy with the term "get" for this functionality. I also ended up splitting it into two functions so that the TypeScript definitions can return more specific types (useful for e.g. the `workDir` option in `std.process`)
The semantics of these new functions are exactly the same as the semantics of `Brioche.get` from #34, except the type of artifact is validated as either a `File` or `Directory` artifact.

Replace `Brioche.get` with `Brioche.includeFile` / `Brioche.includeDirectory`

---

crates/brioche/src/script.rs

This PR fixes a bug related to how imports are handled when transpiling TypeScript to JavaScript. Consider this Brioche project:
```ts
import * as std from "std";
export default async (): Promise<std.Recipe> => {
return Brioche.includeFile("hello.txt");
};
```
When transpiled, the `import "std";` line would get completely dropped because `std` is imported as a value, but is only used at the type level. In this case, this would break global functions like `Brioche.includeFile` and `console.log`, which are supplied by `std`.
The fix is to tweak the transpiler options so imports never get excluded, even if they are only used at the type level.

Fix imports getting excluded when they shouldn't be

---

crates/brioche/src/lib.rs
crates/brioche/src/main.rs
crates/brioche/src/project.rs
crates/brioche/src/publish.rs
crates/brioche/src/references.rs
crates/brioche/src/registry.rs
crates/brioche/src/sync.rs
crates/brioche/tests/brioche_test/mod.rs
crates/brioche/tests/project_load.rs

This PR massively overhauls project publishing: instead of building and uploading a massive JSON representation of all published projects, it now uploads blobs / recipes, then the project JSON, then publishes project tags, in discrete steps. This new implementation also handles the statics included in projects (introduced in #34 / #35).
As part of this change, fetching a project from the registry also now correctly fetches statics for the project.

Overhaul project publishing

---

Cargo.lock
crates/brioche/Cargo.toml
crates/brioche/src/project.rs
crates/brioche/src/project/analyze.rs
crates/brioche/src/script.rs
crates/brioche/tests/project_load.rs
crates/brioche/tests/script_eval.rs
crates/brioche/tests/script_project_analyze.rs

This PR adds support for a new `Brioche.glob` global function. The core idea is very similar to `Brioche.includeFile` / `Brioche.includeDirectory` (#34 / #35): the project analyzer recognizes calls to `Brioche.glob`, looks at the local filesystem, then builds a recipe that can be retrieved with a special op from the JS side. See brioche-dev/brioche-packages#10 for the implementation in `std`
Here's an example:
```ts
// myproject/
//   project.bri
//   Cargo.toml
//   Cargo.lock
//   src/
//     main.rs
import * as std from "std";
// Returns a directory artifact with these entries:
//   Cargo.toml
//   Cargo.lock
//   src/
//     main.rs
export default async () => {
return Brioche.glob("Cargo.lock", "Cargo.toml", "src");
};
```
Glob patterns are matched using the …

Implement `Brioche.glob` global function

---

crates/brioche-core/tests/bake_process.rs
crates/brioche-core/tests/input.rs
crates/brioche-ld/src/main.rs
crates/brioche-pack/src/autowrap.rs
crates/brioche-pack/src/bin/brioche-packer.rs
crates/brioche-pack/src/lib.rs
crates/brioche-pack/src/resources.rs
crates/brioche-packed-exec/src/main.rs
crates/brioche-packed-userland-exec/src/linux.rs

> **Breaking**: This PR changes the schema of the "brioche pack" format for attaching metadata to files. Rather than incrementing the version, this PR updates the `brioche_pack_v0` schema in place, which will change which resources get attached from a process recipe
This PR updates the Brioche pack tools (`brioche-ld`, `brioche-packer`, etc) with a new metadata format, which allows for attaching metadata to ELF files that don't have an interpreter set via the `PT_INTERP` header (e.g. statically-linked ELF files or dynamically linked libraries). This new metadata is specifically used for attaching resources for dependencies of dynamically-linked libraries. So for example, `libcurl.so` has a dependency on `libzstd.so` (among others), so `libzstd.so` would be added in the resources for …

[Breaking] Implement support for resolving transitive dependencies in dynamic libraries

---

crates/brioche-core/src/input.rs
crates/brioche-pack/src/resources.rs

This PR continues the theme of changes from #42 / #43 / #44: some more changes to how resources are handled. This one is smaller and should basically be backwards compatible. Here are the changes:
- Tweak `add_named_blob` function to replace existing symlinks atomically. This led to spooky compiler errors when running highly parallel builds, since these symlinks are used for loading dynamic libraries.
- Update Brioche to error out if a resource in the pack metadata isn't found. Previously, this would only lead to a warning, but I think a hard error is more appropriate. I don't think this errors out if the format is invalid, so there's still some room to tighten it down even more in the future.

Even more resource tweaks

---

Cargo.lock
crates/brioche-core/src/project.rs
crates/brioche-core/src/script/evaluate.rs
crates/brioche/Cargo.toml
crates/brioche/src/build.rs
crates/brioche/src/check.rs
crates/brioche/src/format.rs
crates/brioche/src/install.rs
crates/brioche/src/lsp.rs
crates/brioche/src/main.rs
crates/brioche/src/publish.rs
crates/brioche/src/run.rs
crates/brioche/src/run_sandbox.rs
crates/brioche/src/self_update.rs

This PR makes lots of little quality-of-life tweaks to the CLI:
- Add `brioche install` subcommand. This will install an artifact to `~/.local/share/brioche/installed` (right now, it just outputs to the folder and merges, and also removes the `brioche-run` file from the artifact)
- Add `-r` / `--registry` flag for `build` / `install` / `check`. This allows for using a registry project rather than a local project (meaning you can now run `brioche install -r curl` to install Curl!)
- Add `brioche self-update` subcommand. As the name implies, this updates Brioche itself
- Add help text for all commands / arguments
- Rename `--keep` flag to `--keep-temps` for clarity
- Restructure all CLI commands into separate submodules

CLI improvements

---

crates/brioche-core/src/project.rs
crates/brioche-core/src/registry.rs
crates/brioche-core/src/reporter.rs
crates/brioche-core/tests/brioche_test/mod.rs
crates/brioche-core/tests/project_load.rs

To fetch a project from the registry, we need to fetch all included `.bri` module files, plus any static includes (`Brioche.glob`, etc.). This PR fixes a case where static includes wouldn't be fetched recursively, causing resolve errors like this:
```sh-session
$ brioche run -r hello_world
[100%] Fetched 1 recipe from registry
Error: failed to fetch 'hello_world' from registry
Caused by:
recipes not found: {RecipeHash(Hash("fc51c96ac044e3fb1b6c170146a4df37c4991552f7e99bfe85011358d0456ed8"))}
```
This happened because `hello_world` uses `Brioche.glob`. The top-level globbed directory gets fetched, but the entries for the directory were not being fetched. This PR fixes this bug by doing a deep fetch of recipes from the registry.

Fetch fetching a project form registry failing when project uses includes

---

crates/brioche-core/benches/brioche_bench/mod.rs
crates/brioche-core/src/bake.rs
crates/brioche-core/src/bake/download.rs
crates/brioche-core/src/bake/unarchive.rs
crates/brioche-core/src/blob.rs
crates/brioche-core/src/input.rs
crates/brioche-core/src/registry.rs
crates/brioche-core/src/script.rs
crates/brioche-core/src/sync.rs
crates/brioche-core/tests/brioche_test/mod.rs
crates/brioche-core/tests/output.rs

After a fresh install of Brioche, running `brioche build -r curl` would fail with an error message like `Error: Error: failed to open temp file: Too many open files (os error 24)`. Re-running the command several times would eventually work (because each iteration would make a little more progress), but it's not a great first-time experience.
This PR works around the problem by updating all the functions that save blobs to take a `SaveBlobPermit` type, which wraps a global semaphore (currently set to 10 permits). This prevents trying to open too many file descriptors at once, and this seems to work around the issue on a fairly vanilla Ubuntu setup.
I tried giving it 20 permits as well, but this failed with the same error as before. I'm not sure why trying to save 20+ blobs at a time would …

Use a semaphore to limit the max number of blobs that can be saved at once

---

crates/brioche-pack/src/autowrap.rs
crates/brioche-pack/src/lib.rs
crates/brioche-packed-plain-exec/src/main.rs
crates/brioche-packed-userland-exec/src/linux.rs

This PR adds a new "metadata" variant to the enum of pack formats (used for storing resources, etc.).
For context, the pack format is produced by `brioche-ld` and is used for two purposes:
- It's used by Brioche to attach resources to files
- It's used by `brioche-packed-userland-exec` to determine what libraries, etc. to pass to the program
Since the pack format uses Bincode, adding new fields has been a headache because each side stops understanding the format each time new fields are added. But, I've had to iterate on the format a few times to change how packed executables work, so basically this meant any improvements to packed executables effectively needed to be a breaking change. My reading of the Bincode spec is that enum variants are assigned a variant ID based on their index, …

Add new "metadata" pack format

---

crates/brioche-core/src/registry.rs

Although in the steady state 10 second timeout is reasonable, in practice p100 was observed to be much higher than that (if, for example, the machine you are supposed to talk to needs to cold boot).
Given that just _one_ timeout terminates the entire process, it feels like we can benefit from being quiet a bit more conservative here for the time being.

Bump default timeouts

---

crates/brioche-core/src/bake.rs
crates/brioche-core/src/bake/collect_references.rs
crates/brioche-core/src/recipe.rs
crates/brioche-core/src/references.rs
crates/brioche-core/tests/bake_collect_references.rs

This PR adds a new type of recipe, called `collect_references`. It takes a directory recipes, and bakes to the same value, then adds in a `brioche-resources.d` directory containing all the references from all descendent artifacts within (and then removes the reference from each artifact).
This effectively mirrors how `brioche build -o <directory>` works, and is specifically meant to improve situations where we need to create a self-contained tarfile of a Brioche artifact within Brioche itself. A real-world use-case can be seen in `std.ociContainerImage`, where we currently need to effectively manually do what this new recipe does in a messier way (see the [`expandResources`](https://github.com/brioche-dev/brioche-packages/blob/9fd51090a56cf83f4aa9c5002b78f2b2054ad3ad/packages/std/extra/oci …

Add new `collect_references` recipe

---

crates/brioche-core/src/project.rs

This PR improves how project downloads are handled from the registry:
- Project dependencies are now downloaded in parallel. This might turn out to be problematic in the future because this download is recursive but has no semaphore to cap the total number of recursive downloads. This should suffice for a while (and I'm not confident enough in how to solve this in a way that wouldn't deadlock)
- Project module blobs are now downloaded with the `brioche_core::registry::fetch_blobs` function, which will both download blobs in parallel and avoid downloading blobs that have been downloaded before

Parallelize downloading project deps and blobs from registry

---

crates/brioche-core/src/script/js.rs

This PR adds a new op named `Deno.core.ops.op_brioche_version`, which just returns the version of the `brioche-core` crate. This is primarily meant to be used to start using new recipes in `std` without breaking backwards compatibility. Of course, proper feature detection would be better long-term, but this is a quick-and-easy option for the time being.

Add new JS op to get current Brioche version

---

crates/brioche-core/src/script/js.rs
crates/brioche-core/tests/script_ops.rs

This PR is a followup to #59. For some reason, the op as previously defined wasn't showing up in `Deno.core.ops`. I have no clue why, but the `#[deno_core::op]` attribute has been deprecated anyway, so I don't think it's worth investigating what went wrong here. There is a test now to make sure the op works.

Fix Deno ops not including `op_brioche_version`

---

crates/brioche-core/src/input.rs
crates/brioche-pack/src/lib.rs

This PR makes some breaking changes to the functions in the `brioche_pack` crate:
- `brioche_pack::extract_pack` now requires a reader that implements [`std::io::Seek`](https://doc.rust-lang.org/stable/std/io/trait.Seek.html). The implementation also no longer needs to read the full file into memory to extract the pack
- `brioche_pack::extract_pack` now returns a new `ExtractedPack` data type, which includes both the pack plus the length of the unpacked data
- `brioche_pack::inject_pack` now returns the number of bytes appended to the reader
The lengths returned will allow callers to manipulate the pack data more directly, such as by stripping the packed data from a file using [`std::fs::File::set_len()`](https://doc.rust-lang.org/stable/std/fs/struct.File.html#method.set_len)

Improve utils in `brioche-pack`

---

crates/brioche-core/src/recipe.rs
crates/brioche-core/src/references.rs

This PR fixes a failure that cropped up in the `brioche-packages` repo (e.g. in [CI #148](https://github.com/brioche-dev/brioche-packages/actions/runs/9805784766)) with the following error message:
> Error: error returned from database: (code: 1) too many SQL variables: (code: 1) too many SQL variables
I was able to reproduce locally by moving my `~/.local/share/brioche` directory somewhere else then running `brioche build -p ./packages/nushell`. This resulted too many SQLite variables being used in a single query (the limit is either 999 or 32,766 depending on the SQLite version)
The fix in this PR is simple: batch the query to limit the max number of records fetched / inserted per query, thereby limiting the number of SQLite variables used

Fix more instances of SQLite "too many variables" errors

---

crates/brioche-core/src/output.rs

Resolve #73.
I just embedded `options.output_path`where it was making sense to have it.

Improve error messages in setting output file permissions and modified time

---

crates/brioche-core/src/script/compiler_host.rs
crates/brioche-pack/src/encoding.rs

Fix the two following warnings with clippy 1.79.0:
```bash
warning: struct `AsPath` is never constructed
--> crates/brioche-pack/src/encoding.rs:37:12
|
37 | pub struct AsPath<T>(std::marker::PhantomData<T>);
|            ^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: assigning the result of `ToOwned::to_owned()` may be inefficient
--> crates/brioche-core/src/script/compiler_host.rs:165:25
|
165 |                         *doc_contents = contents.to_owned();
|                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_into()`: `contents.clone_into(doc_contents)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
= note: `#[warn(clippy::assigning_clones)]` on by default
```

[Rust] Resolve Clippy warnings

---

Cargo.lock
crates/brioche-core/Cargo.toml

Building on nightly is not possible due to not having the upstream `ahash` bug fix from https://github.com/tkaitchuck/aHash/pull/183:
```bash
error[E0635]: unknown feature `stdsimd`
--> /Users/jaudiger/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.6/src/lib.rs:99:42
|
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
|
```
On the current main branch, we have two `ahash` dependencies:
- one on version 0.8.6
- the other on version 0.7.7
The resolution of the bug was done in the version 0.8.7: https://github.com/tkaitchuck/aHash/releases/tag/0.8.7.
In order to build brioche on nightly, I did two things (separated in two commits):
- First commit is to get rid of the old `ahash 0.7.7` dep by updating deno_ast to 0.28.0: …

[Rust] Fix nightly build

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-pack/Cargo.toml

Based on #82.
`cargo udeps`can be used to find unused dependencies with `cargo +nightly udeps`. Current report on main:
```bash
`brioche-core v0.1.1 (/Users/jaudiger/Development/git-repositories/jaudiger/brioche/crates/brioche-core)`
└─── dependencies
├─── "fs_extra"
`brioche-pack v0.1.1 (/Users/jaudiger/Development/git-repositories/jaudiger/brioche/crates/brioche-pack)`
└─── dependencies
├─── "blake3"
├─── "goblin"
├─── "pathdiff"
└─── "ulid"
```

[Cargo] Remove unused deps

---

crates/brioche/src/format.rs

Add the ability to format more than one project at a time by authorizing the usage of multiple `-p` arguments.
Part of https://github.com/brioche-dev/brioche/issues/75

feat: add the ability to format more than one project at a time.

---

crates/brioche-core/src/script/format.rs
crates/brioche/src/format.rs

Resolve #85 
Add the formatted files and better handle errors happened on a project when formatting more than once at the same time as suggested by @kylewlacy https://github.com/brioche-dev/brioche/pull/84#pullrequestreview-2174249892

feat: rewrite the format function

---

Cargo.lock
crates/brioche-core/Cargo.toml

Start to update some dependencies that require a major bum of their version, which could in turn imply a breaking change in Brioche codebase. But nothing was impacted us, so far. And Brioche MSRV wasn't impacted. It was verified with `cargo msrv verify` command:
```bash
Fetching index
Verifying the Minimum Supported Rust Version (MSRV) for toolchain aarch64-apple-darwin
Using check command cargo check
Finished Satisfied MSRV check: 1.77.2 ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 00:01:48
```
Part of #81

[Build] Update dependencies

---

crates/brioche/src/format.rs
crates/brioche/src/publish.rs

Resolve #87.
To be reviewed one commit at a time. The last commit could be removed from this PR, since it has no impact on resolving the issue #87. I just found a quick refactoring which led to suppressing a return statement.
Before the fix, reformatting multiple projects at once was printing:
```bash
[826µs] 0 / 0 jobs complete
[102.8ms] 0 / 0 jobs complete
All files of project '../brioche-packages/packages/biome' are formatted
```
After the fix, the command is now correctly printing its output:
```bash
All files of project '../brioche-packages/packages/go' are formatted
All files of project '../brioche-packages/packages/biome' are formatted
Error occurred while formatting project '../brioche-packages/packages/g': failed to canonicalize path ../brioche-packages/packages/g
```

Fix print issue with reporter

---

crates/brioche/src/check.rs
crates/brioche/src/format.rs
crates/brioche/src/main.rs

Part of https://github.com/brioche-dev/brioche/issues/75
I added the ability to set more than one registry and project when calling `brioche check` command. This is separated in two commits. The first updates the check command, while the second commit refactor the code of the format command to mimic what was done with the check.
This has been done to extend more easily the next commands, cited in https://github.com/brioche-dev/brioche/issues/75.

[CLI] Check with multiple arguments

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/script.rs
crates/brioche-core/src/script/check.rs
crates/brioche-core/src/script/compiler_host.rs
crates/brioche-core/src/script/evaluate.rs
crates/brioche-core/src/script/js.rs
crates/brioche-core/src/script/lsp.rs

Part of #81 
I didn't update the Deno dependencies to their latest version to reduce the possibility of regression due to breaking changes in the APIs. A lot of things have changed since version `0.201.0` of deno_core. The main modification in this PR is the usage of `op2` in replacement of `op` (which was already deprecated in `0.201.0`). `op` has been removed in favor of the new one. The new syntax is more verbose, but provides better constraining.
I updated it to `0.237.0` and kept in sync `serde_v8` to `0.146.0`. Starting version `0.238.0`, there are other breaking changes that will be part of another PR.
I tested the modification with the following brioche commands:
```bash
brioche fmt -p packages/bat
brioche check -p packages/bat
brioche build -p packages/bat
brioche build -p …
```

[Cargo] Update deno dependencies (not the latest version)

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/script.rs
crates/brioche-core/src/script/check.rs
crates/brioche-core/src/script/compiler_host.rs
crates/brioche-core/src/script/evaluate.rs
crates/brioche-core/src/script/js.rs
crates/brioche-core/src/script/lsp.rs

Reverts brioche-dev/brioche#93
See #98 for discussion about the stack frame bug leading to this revert. This is temporary until a fix on the newer Deno version is in place

Revert "[Cargo] Update deno dependencies (not the latest version)"

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/script.rs
crates/brioche-core/src/script/check.rs
crates/brioche-core/src/script/compiler_host.rs
crates/brioche-core/src/script/evaluate.rs
crates/brioche-core/src/script/js.rs
crates/brioche-core/src/script/lsp.rs
crates/brioche-core/tests/script_ops.rs

This PR restores the `deno_core` updates from #93 (which was originally reverted in #99), along with a fix to the how stack frames are resolved in scripts
The discussion in #98 has more context, but to summarize:
1. In [`deno_core` v0.215.0](https://github.com/denoland/deno_core/compare/0.214.0...0.215.0), the function `Deno.core.prepareStackTrace` was no longer being set and instead defined directly on `Error.prepareStackTrace`
2. (1) made it so the script where we were setting `Error.prepareStackTrace` was wrong, and was just clearing out the `prepareStackTrace` function instead
3. To resolve statics like `Brioche.glob`, the `std` package uses error stack traces to determine which project to resolve the glob from. This broke due to (2)
The fix was then to just remove the line where we …

Restore `deno_core` update and fix stack frames

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/script.rs

Part of https://github.com/brioche-dev/brioche/issues/81
New clean branch based on https://github.com/brioche-dev/brioche/pull/98 + the latest commits on main.
I tested the modification with the following brioche commands:
```bash
brioche fmt -p packages/bat
brioche check -p packages/bat
brioche build -p packages/bat -o /tmp/bat
brioche build -p packages/bat -e test -o /tmp/bat_test
brioche install -p packages/bat
brioche run -p examples/nodejs_frontend 
```

build: update deno_ast dependency to latest version

---

crates/brioche-core/src/bake.rs

Part of https://github.com/brioche-dev/brioche/issues/103
I had these changes locally to investigate why the Ruff folder was containing more than one element:
```bash
Error: tried peeling 2 entries of Directory { entries: {"64f43441c8d3a0e9315e5de1d5e644b0d097e7cc.data": WithMeta { value: RecipeHash(Hash("0fda9b496eb36343c511b5caf5339a8dfcb6a1626586425fdd2daa67f796b2c3")), meta: Meta { source: None } }, "ruff-0.5.3": WithMeta { value: RecipeHash(Hash("545ec949c9a242c508a690a5f2a14b63361008417cba1ff67cdaa6692c815ccd")), meta: Meta { source: None } }} }
```
The first commit is opinionated, since I wanted to print the number of entries inside the directory and the directory itself.
My second commit is maybe not necessary, the user should be aware that peeling with a depth of 0 will output …

Update peel error logs, and constrain its arguments

---

crates/brioche/src/publish.rs

Part of https://github.com/brioche-dev/brioche/issues/75
Similar to what's already done for check and format commands, but this time for the publish command. Now you could give multiple projects to publish all of them in a single call:
```bash
brioche publish -p packages/foo -p packages/bar
```

feat: add ability to specify multiple projects while publishing

---

crates/brioche/src/check.rs
crates/brioche/src/install.rs

Part of https://github.com/brioche-dev/brioche/issues/75
Similar to what's already done for other commands, but this time for the install command. Now you could give multiple projects to install all of them in a single call:
```bash
brioche install -p packages/foo -p packages/bar
```

feat: add ability to specify multiple projects while installing

---

crates/brioche-core/src/bake/download.rs
crates/brioche-core/src/download.rs
crates/brioche-core/src/lib.rs
crates/brioche-core/src/project.rs
crates/brioche-core/src/project/analyze.rs
crates/brioche-core/src/references.rs
crates/brioche-core/src/script.rs
crates/brioche-core/tests/project_load.rs
crates/brioche-core/tests/script_eval.rs

Companion PR: brioche-dev/brioche-packages#75
Part of #70
This PR updates the project analysis in Brioche to find instances of `Brioche.download("...")`, then to download the referenced URL and record the hash in the lockfile (without requiring the user to specify the hash directly). This only works when the argument is a literal string, and it will fail at analysis time and at runtime otherwise. This is in line with the other "statics" that are implemented today (`Brioche.glob`, `Brioche.includeFile` `Brioche.includeDirectory`).
As with the other statics, the _runtime implementation_ of `Brioche.download` is not in the `brioche` repo, but will instead be part of the `std` package.
Here's a usage example:
```typescript
// The hash will be recorded in `brioche.lock`
const source = …
```

Add support for `Brioche.download()` for locked downloads

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/reporter.rs

Update all the opentelemetry crates. `opentelemetry-jaeger` dependency was deprecated in favor of `opentelemetry-otlp` which provides agnostic APIs to export traces, logs, metrics.
Unfortunately, due to `console-subscriber` we now have to duplicate some dependencies such as `tonic`...
It depends on the unreleased version 0.25.0 of `tracing-opentelemetry`, see PR (for context: https://github.com/tokio-rs/tracing-opentelemetry/pull/155)

[Cargo] Update opentelemetry crates to their latest version

---

Cargo.lock
crates/brioche-core/Cargo.toml

Just update `console-subscriber` and `deno_ast`

chore: update console-subscriber and deno_ast dependencies

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/script.rs
crates/brioche-core/src/script/bridge.rs
crates/brioche-core/src/script/check.rs
crates/brioche-core/src/script/compiler_host.rs
crates/brioche-core/src/script/evaluate.rs
crates/brioche-core/src/script/lsp.rs
crates/brioche/src/lsp.rs
rust-toolchain.toml

Resolve #81 
This PR update `deno_core`and `serde_v8` to their latest version. I also made the switch to the usage of Rust 1.79, since deno_core requires it to make use of https://github.com/rust-lang/rust/pull/104087/.

Update deno crates to latest version

---

crates/brioche/src/self_update.rs

The code changes in `self_update.rs` add logic to set the executable bit on the `brioche` binary if it's not already set. This ensures that the binary can be executed properly after a self update.
Resolve https://github.com/brioche-dev/brioche/issues/95

fix: set executable bit on brioche binary if not already set

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/bake.rs
crates/brioche-core/src/recipe.rs
crates/brioche-core/src/references.rs
crates/brioche-core/tests/bake_glob.rs

Implement new `glob` recipe

---

crates/brioche-core/src/output.rs

This PR reverts the changes made to `create_output` from #115. The change in question was to use a hashmap to memoize which output paths had been written when `create_output` was called (the goal was to avoid writing to the same path multiple times)
It turns out this change could cause severe slowdowns in some cases. I started digging into why building the [eza](https://github.com/brioche-dev/brioche-packages/tree/77e0da6af50ace3dea6ea9eab494ffadd1344aad/packages/eza) package locally was taking so long-- around 3-4 minutes-- even though the actual Rust build was pretty fast (about 30 seconds). I tested again with a version of Brioche before #115, and the build was much faster: about 1m18s
I did lots of experiments and rebuilds, and finally narrowed the problem down to `create_output`. …

Revert `create_output` memoization

---

crates/brioche-core/benches/bake.rs
crates/brioche-core/benches/directory.rs
crates/brioche-core/src/bake.rs
crates/brioche-core/src/bake/collect_references.rs
crates/brioche-core/src/bake/process.rs
crates/brioche-core/src/input.rs
crates/brioche-core/src/output.rs
crates/brioche-core/src/project.rs
crates/brioche-core/src/recipe.rs
crates/brioche-core/src/references.rs
crates/brioche-core/tests/bake_process.rs
crates/brioche-core/tests/directory.rs
crates/brioche-test-support/src/lib.rs

The `WithMeta` type is used to track the stack trace a recipe was created in TypeScript: since recipe evaluation is lazy, it can be really hard to track this down from just the recipes themselves. This metadata isn't used at all in Brioche today, but the eventual goal is to give better error messages (e.g. when a build fails, we could point to the line in TypeScript where the error occurred)
Turns out, this metadata wasn't properly being deserialized when going from TypeScript to Rust, so it always came back empty. This PR fixes that, and makes a few changes so the `WithMeta<_>` wrapper type is a bit simpler:
- Update `serde::Deserialize` impl on `WithMeta<_>` to try and deserialize the `meta` field (serialization still skips it). This also means the type that `WithMeta` wraps must now …

Clean up `WithMeta` handling

---

crates/brioche-core/src/recipe.rs
crates/brioche-core/src/references.rs
crates/brioche-core/src/registry.rs
crates/brioche-core/src/sync.rs
crates/brioche-core/tests/recipe.rs
crates/brioche-core/tests/sync_to_registry.rs

This PR fixes an issue where calling `brioche build --sync` would end up missing some recipes while syncing. The result was that running e.g. `brioche install -r eza` would end up needing to build the Rust crate, even though the latest version had been built and synced from [`brioche-packages`](https://github.com/brioche-dev/brioche-packages)
This was caused by the function `brioche_core::references::recipe_references` missing recipes in some cases. ~~Basically, this function wouldn't return child recipes directly, but would skip straight to returning the grandchild recipe dependencies-- effectively skipping a layer of dependencies. If this skipped layer included "expensive" recipes, then that would lead to cases like those seen with `eza` where the user would end up baking the expensive …

Fix `--sync` missing some recipes

---

crates/brioche-core/src/recipe.rs
crates/brioche-core/src/references.rs
crates/brioche-core/src/registry.rs
crates/brioche-core/src/sync.rs
crates/brioche-core/tests/recipe.rs
crates/brioche-core/tests/sync_to_registry.rs

Reverts brioche-dev/brioche#122
Okay, it finally hit me what was happening...
So the way it was previously implemented `--sync` would find all top-level recipes for a build, then would sync them plus any recipes that they referenced _by hash_. #122 changed it so it would find _all_ internal recipes, either by hash or nested directly. The PR changed it so these internal recipes would be synced too
I think it would be a valid decision to sync these internal recipes, but for the purposes of `--sync`, I think it's the wrong choice. Namely, it just pollutes the registry with some recipes that should never get directly downloaded (clients only download the recipes referenced by hash, they would never have a need to download a recipe embedded directly)
As for the issue with `eza`, I finally …

Revert "Fix `--sync` missing some recipes"

---

crates/brioche-core/src/fs_utils.rs
crates/brioche-core/src/input.rs
crates/brioche-core/tests/bake_process.rs

This PR fixes some issues around symlink handling in the `create_input` function. I found this after finding a bug introduced by #115, but also found some other issues too.
First, when calling `create_input` on a directory, if two files refer to the same resource path and that path is a symlink, then that resource would only get added to one of the files. This was due to some unsound memoization, which has now been removed.
Second, the way that symlink resources were canonicalized meant that, in some situations, `create_input` could end up creating a directory structure that didn't match the input. I worked out two such cases:
1. When a symlink's target points to another symlink (`link1 -> link2`, `link2 -> target`)
2. When a symlink's target has another symlink as a path component …

Tweak symlinks in `create_input`

---

crates/brioche-core/src/bake/process.rs
crates/brioche-core/src/bake/unarchive.rs
crates/brioche-core/src/blob.rs
crates/brioche-core/src/registry.rs
crates/brioche-core/src/script/bridge.rs
crates/brioche-core/src/sync.rs
crates/brioche-core/tests/bake_process.rs

This PR updates how the `dependencies` field is use when a `process` recipe is baked. Each dependency recipe can contain a `brioche-env.d/env` directory to set env vars on the process, but previously this was limited to appending `$PATH`-like env vars: each entry in `brioche-env.d/env` had to be a directory (whose name was an env var), where each entry within was a symlink, whose target would be appended to the env var (separated by `:`).
This PR lifts the restriction, and now each env var within `brioche-env.d/env` can either be a file, directory, or symlink:
- **Directory**: Same behavior as before. Each entry within the directory must be a symlink whose target is appended to the env var (the name of the symlink doesn't matter)
- **Symlink**: If the env var is empty, then it will be set …

Update `Process.dependencies` to allow more flexibility when setting envs

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/download.rs
crates/brioche-core/src/project.rs
crates/brioche-core/src/project/analyze.rs
crates/brioche-core/src/references.rs
crates/brioche-core/src/script.rs
crates/brioche-core/src/script/bridge.rs
crates/brioche-core/tests/script_eval.rs

Closes #96 
This PR updates project analysis to look for calls to `Brioche.gitRef(...)`, to then find the commit hash for the provided ref from the given git repository, and to record the result in the lockfile (similar to `Brioche.download(...)` from #102). Just like the other "statics", we need to be able to resolve the inputs to `Brioche.gitRef(...)` entirely statically (either string literals, or a subset of JS templates supported by #118).
Unlike the other statics, `Brioche.gitRef` does not resolve to a recipe. Instead, it resolves to an object containing the properties `repository` and `commit`. To account for this change, the output of the function `op_brioche_get_static` has been changed to an object with a `staticKind` field, which will look like one of these:
```yaml
{ …
```

Add support for `Brioche.gitRef()` for locked git refs

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/bake/unarchive.rs
crates/brioche-core/src/blob.rs

Closes #103
This PR updates the `unarchive` recipe to use the [`tar`](https://crates.io/crates/tar) crate (actively maintained, but sync-only) instead of the [`tokio-tar`](https://crates.io/crates/tokio-tar) crate (async, but apparently unmaintained). This was specifically done to address the bug seen in #103, where tarfiles with long names weren't getting handled properly
I referenced #117 as inspiration, but ended up with a few different decisions in the implementation. Namely, the sync work happens in a `spawn_blocking` Tokio task, and uses a channel for the async parts (actually building the artifacts, which boil down to database writes). I also used [`tokio_util::io::SyncIoBridge`](https://docs.rs/tokio-util/0.7.12/tokio_util/io/struct.SyncIoBridge.html) so that we could keep doing …

Update unarchive to use `tar` crate instead of `tokio_tar`

---

crates/brioche-core/src/project.rs

Closes #129 
This PR tweaks the `load_project` function, which is where lockfiles are generated and updated. In this code, we were skipping over `Brioche.download` and `Brioche.gitRef` statics in the context of the LSP (where `fully_valid` is false), which meant that the lockfile that got built by the LSP would never have any download or git ref statics in it. When the LSP saves a file, we would write this recomputed lockfile (in order to update dependencies, which were handled correctly). The updated lockfile would therefore save as if the project had no `Brioche.download` or `Brioche.gitRef` statics included, removing them even if they were already present in the existing lockfile.
As a fix, we just copy over the `Brioche.download` and `Brioche.gitRef` statics from the existing lockfile …

Fix LSP removing static downloads and git refs from lockfile on save

---

crates/brioche-core/src/project.rs

Closes #128 
This PR updates the `fetch_project_from_registry` function to use a mutex to ensure that the same project doesn't get cloned more than once at a time. This works by using a `BTreeMap` (wrapped in a `Mutex`), where each key-value pair is a project hash and another mutex
As far as implementation, there are a few other places in the code where we have a similar problem of wanting to ensure that a piece of code only runs once for a particular key: baking recipes, and creating outputs. For baking, we use a map that contains channels, which allows parallel calls to get the result immediately without doing more work. For creating outputs, we use a lazier option of using a single mutex to guard the whole section-- it's not (currently) fine-grained. This new implementation is kind of …

Fix race condition when trying to fetch the same project from the registry more than once

---

crates/brioche-core/src/script/lsp.rs

Closes #113 
This PR fixes the "Request textDocument/diagnostic failed" error that the Brioche LSP would emit whenever a new file was opened. The fix was basically to re-add the previously commented-out implementation of the LSP `diagnostic` method implementation, and to update it to ensure the specified document was loaded before trying to get diagnostics

Handle LSP "diagnostic" message to fix "diagnostic failed" error

---

crates/brioche-core/src/project.rs
crates/brioche-core/src/script/bridge.rs
crates/brioche-core/src/script/lsp.rs
crates/brioche-core/tests/project_load.rs
crates/brioche-test-support/src/lib.rs
crates/brioche/src/build.rs
crates/brioche/src/check.rs
crates/brioche/src/format.rs
crates/brioche/src/install.rs
crates/brioche/src/main.rs
crates/brioche/src/publish.rs
crates/brioche/src/run.rs

This PR updates several subcommands with a new `--locked` flag, namely `build`, `check`, `run`, and `install`. When used, the command will fail unless the lockfiles are up-to-date.
The main motivation for this change is for use in CI, such as in the `brioche-packages` repo (see brioche-dev/brioche-packages#111 for an example of a PR that got through with an out-of-date lockfile)
Currently, the error messages leave a lot to be desired... here's an example error:
```
Error occurred with project './packages/hello_world': project load errors: [FailedToLoadDependency { name: "std", cause: "hash for download 'https://example.com/' not found in lockfile" }]
```

Add `--locked` flag for several subcommands

---

crates/brioche-core/runtime/src/lsp.ts
crates/brioche-core/src/script/lsp.rs

This PR makes some minor tweaks to the LSP that should resolve a few errors and exceptions:
- Log warning message when deserializing response from LSP fails (this should help debug future failures)
- Prevent `Lsp.diagnostic()` from returning out-of-bounds line / column numbers causing deserialization error
- Catch exceptions from `ts.getPositionOfLineAndCharacter()`

Fix some LSP errors from converting between line / column numbers and positions

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/output.rs
crates/brioche-core/src/recipe.rs
crates/brioche-core/src/references.rs
crates/brioche-core/src/reporter/console.rs
crates/brioche-core/src/script.rs
crates/brioche-core/tests/bake_cache.rs
crates/brioche-core/tests/bake_download.rs
crates/brioche-core/tests/bake_parallel.rs
crates/brioche-core/tests/bake_process.rs
crates/brioche-core/tests/project_load.rs
crates/brioche-core/tests/script_eval.rs
crates/brioche-pack/Cargo.toml
crates/brioche-test-support/Cargo.toml
crates/brioche/Cargo.toml

Pretty self-explanatory, this updates all deps to the latest versions (using `cargo upgrade --incompatible` from `cargo-edit`). There were only a few minor breakages around Mockito, Deno, and OpenTelemetry

Update all Rust deps

---

crates/brioche-core/src/reporter/console.rs
crates/brioche/src/build.rs
crates/brioche/src/check.rs
crates/brioche/src/format.rs
crates/brioche/src/install.rs
crates/brioche/src/main.rs
crates/brioche/src/publish.rs
crates/brioche/src/run.rs

This PR adds a new `--display` flag to most CLI commands (specifically, those that create a console output reporter). This flag takes 4 different options:
- `--display console` - Enable pretty (SuperConsole-based) console output
- `--display plain` - Enable plaintext-only output
- `--display auto` Use `console` or `plain` based on if stderr is a tty or not (default, matches current behavior)
- `--display plain-reduced` - New format: plaintext-only output, but don't show process outputs
The main motivation for the new `plain-reduced` format is for GitHub Actions runs, where log outputs are so long that it actually makes it difficult to view a failed build in the browser. Instead of trying to log the build outputs during the build, we can instead just show a bit of the output from the …

Add reduced plaintext output format

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/reporter.rs
crates/brioche-core/src/reporter/console.rs

This PR fixes some issues around OpenTelemetry following #140: namely, trying to use `BRIOCHE_ENABLE_OTEL=1` would cause a deadlock, and even after fixing that, events wouldn't be flushed properly. There were two fixes involved:
1. Enable Tokio batched OpenTelemetry exporter. This fixes a panic that was silently being ignored, caused by some HTTP code trying to access the Tokio runtime on a non-Tokio thread
2. Update OpenTelemetry shutdown code. `opentelemetry::global::shutdown_tracer_provider()`  no longer seems to do it. Now, we explicitly shut down the tracer provider directly.

Fix OpenTelemetry runtime and shutdown

---

Cargo.lock
crates/brioche-core/src/bake.rs
crates/brioche-core/src/bake/process.rs
crates/brioche-core/src/registry.rs
crates/brioche-core/tests/bake_process.rs
crates/brioche-test-support/Cargo.toml
crates/brioche-test-support/src/lib.rs

This PR speeds up `cargo test` tests, namely those under `bake_process`.
The main discovery I made was that every registry hit was getting a 501 response, which is what Mockito returns when a URL isn't stubbed. This in turn triggered the `reqwest-retry` middleware, causing it to try the same request again after a delay, until it reached the maximum number of retries. So, there was an unnecessary ~5s pause per (expensive) baked recipe in the tests...
This PR fixes that by disabling the retry middleware for tests. Additionally, it splits the `bake_process` tests up into separate tests again, along with some extra caching around the rootfs files needed when baking processes.

Speed up tests

---

crates/brioche-core/src/bake/process.rs
crates/brioche-core/src/process_events/writer.rs

This is a small PR that updates the process events writer (see #138) so the process description is split into a new frame and flushed immediately, even before the process runs.
The main motivation here is, if you see an `events.bin.zst` file on disk, you should be able to inspect it to see which process it's for right away without waiting for it to hit a frame size of 1MB.

Add frame to process events after writing description

---

crates/brioche-core/src/bake.rs
crates/brioche-core/src/bake/attach_resources.rs
crates/brioche-core/src/input.rs
crates/brioche-core/src/recipe.rs
crates/brioche-core/src/references.rs
crates/brioche-core/tests/bake_attach_resources.rs
crates/brioche-core/tests/input.rs
crates/brioche-test-support/src/lib.rs

This PR adds a new `attach_resources` recipe. It takes a directory recipe, finds all files with resources, then tries to resolve the resources by looking for a `brioche-resources.d` directory. This is effectively the opposite operation from `collect_references` introduced in #57.
The main motivation for this change was while I was investigating #147. As outlined in [this comment](https://github.com/brioche-dev/brioche/issues/147#issuecomment-2543982526), the short-term plan was to tar then untar the `std.toolchain()` recipe. `collect_references` is suitable for tarring, but we needed an operation to re-add resources back into a recipe after untarring.
Locally, here's a little function I've been playing with, which I think will do the job:
```typescript
/**
* Sync a recipe by creating an …
```

Add new `attach_resources` recipe

---

.github/workflows/ci.yml
Cargo.lock
crates/brioche-core/src/bake/process.rs
crates/brioche-core/src/platform.rs
crates/brioche/Cargo.toml

This PR adds initial support for process recipes with `aarch64-linux` as a platform. This basically entailed 3 minor changes:
1. Added `aarch64-linux` as a new platform enum, which can be returned by the `current_platform` function.
2. Added process rootfs recipes for `aarch64-linux`. These were pre-existing downloads that were already saved under the `development-content.brioche.dev` site, so it was just a matter of selecting the right URL and hash based on the platform.
3. Tweaked the `bake_process` function to validate the platform. This was an oversight where there was no validation that we were actually building for the platform specified by the `platform` field in the process recipe!
Also as part of this PR, I updated the CI/CD pipeline to build Brioche for `aarch64-linux`

Add initial support for `aarch64-linux`

---

.github/workflows/ci.yml

This PR updates the GitHub Actions workflows so all Ubuntu-based jobs use Ubuntu 24.04.
Between 22.04 and 24.04, [Ubuntu started restricting unprivileged user namespaces](https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces), which Brioche uses for sandboxing. So, the main change in this PR was to enable unprivileged user namespaces when running tests on Ubuntu by using a sysctl config file.

Update GitHub Actions jobs to use Ubuntu 24.04

---

.github/workflows/ci.yml

After merging #151, I caught a build failure in the `brioche-packages` repo (still using Ubuntu 22.04 currently). The build failure looked to be caused by the latest Brioche build depending on a newer version of glibc. As a simple workaround, this PR updates the GitHub Actions workflow so the Brioche binary is once again built on Ubuntu 22.04 instead of Ubuntu 24.04.
Other workflows still use Ubuntu 24.04 as appropriate, and additionally tests now run with both Ubuntu 22.04 and 24.04.
Once #51 is addressed, this should no longer be an issue (as Brioche itself would no longer directly depend on the system's glibc).

Update GitHub Actions workflow to use Ubuntu 22.04 for build

---

.gitattributes
.github/workflows/ci.yml
brioche.lock
project.bri

Part of #51
This PR adds a `project.bri` file to the repo root, which defines a [Brioche project](https://brioche.dev/docs/core-concepts/projects/) for Brioche itself. Running `brioche build` within the repo will build a full release build of Brioche.
Since this build is built with Brioche, this packs Brioche itself as a [packed executable](https://brioche.dev/docs/how-it-works/packed-executables/)! The result should be able to run on any x86-64 Linux environment, even those without a normal glibc environment (e.g. Alpine, NixOS, etc).
This PR also updates the GitHub Actions workflow to run the build, and also to upload it as a tarball under `https://development-content.brioche.dev` (although I'd strongly recommend _not_ directly referring to this URL for anything important!)
There are …

Add `project.bri` to build Brioche with Brioche

---

.github/workflows/ci.yml
brioche.lock
crates/brioche/Cargo.toml
crates/brioche/src/self_update.rs
project.bri

This PR makes changes to the `brioche` crate and to `project.bri` so that, when Brioche is used to build Brioche itself as a [packed executable](https://brioche.dev/docs/how-it-works/packed-executables/), the `brioche self-update` command is disabled in the resulting build of Brioche.
This change was done purely because `brioche self-update` assumes that Brioche is installed as a single, standalone executable, which is not true when it's distributed as a packed executable. Longer term, the better solution would definitely be to update `brioche self-update` to support updating either a standalone executable or a packed executable.
Here's what this PR changed:
- Update `brioche` crate with new `self-update` feature, which is enabled by default. When it's _disabled_, the `brioche …

Disable self-update command in packed Brioche builds

---

README.md

This PR updates the installation script in `README.md` to use `curl ... | sh` rather than `curl ... | bash`.
We can make this change thanks to the installation script changes in brioche-dev/brioche.dev#12, and the new snippet in this PR matches the snippet that's now used on https://brioche.dev.

Update installation snippet in README

---

Cargo.toml
crates/brioche-core/Cargo.toml
crates/brioche-core/src/bake/process.rs
crates/brioche-core/src/sandbox.rs
crates/brioche-core/src/sandbox/linux_namespace.rs
crates/brioche-pack/Cargo.toml
crates/brioche-test-support/Cargo.toml
crates/brioche/Cargo.toml

This PR prepares for Rust Edition 2024 by refactoring the edition in the main Cargo file.
I also re-factored at root level the settings of cargo clippy without enabling new lint. And I also fixed a few lints found on darwin.
What could be done easier in a future with this approach:
- Defining the Rust version at root level
- Enabling new lints

Update cargo workspace and resolve a few lints on darwin

---

Cargo.toml
crates/brioche-core/Cargo.toml
crates/brioche-pack/Cargo.toml
crates/brioche-test-support/Cargo.toml
crates/brioche/Cargo.toml
rust-toolchain.toml

Set the `rust-version` workspace field to make it easier to update it in the future.

feat: update Rust version to 1.84 in Cargo.toml files

---

crates/brioche-core/src/bake.rs
crates/brioche-core/src/bake/process.rs
crates/brioche-core/src/input.rs
crates/brioche-core/src/lib.rs
crates/brioche-core/src/output.rs
crates/brioche-core/src/references.rs
crates/brioche-core/src/reporter.rs
crates/brioche-core/src/script/bridge.rs
crates/brioche-core/src/sync.rs
crates/brioche/src/build.rs
crates/brioche/src/install.rs
crates/brioche/src/run.rs

This PR cleans up the `#[tracing::instrument]` attributes and `.instrument()` futures calls to greatly improve how readable Brioche's OpenTelemetry output (i.e. when running Brioche with `$BRIOCHE_ENABLE_OTEL=1` and `$OTEL_EXPORTER_OTLP_ENDPOINT` set to an endpoint for Jaeger or another collector). Basically, I cut out deeply-nested recursive functions, since the extra output from nesting made the output completely unusable.
Here's an example of what the output looks like now:

Clean up tracing output

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche/Cargo.toml

Just to clean up the features we are using from tokio-utils. I would prefer to enable the feature one by one instead of just setting the flag "full". I'll I think do the same thing, later, for the tokio dependency.

Update tokio-utils features

---

crates/brioche-core/src/bake/process.rs
crates/brioche-core/src/blob.rs
crates/brioche-core/src/lib.rs
crates/brioche-core/src/output.rs
crates/brioche-core/src/project.rs
crates/brioche-core/tests/project_load.rs
crates/brioche-test-support/src/lib.rs
crates/brioche/src/install.rs

This PR updates the `Brioche` type to use the `$BRIOCHE_DATA_DIR` env var to set the base path for the local Brioche files. This overrides the paths used for storing artifacts, blobs, projects, installed packages, etc. (the default path is still `~/.local/share/brioche` on Linux, as determined by the method [ProjectDirs::data_local_dir](https://docs.rs/directories/6.0.0/directories/struct.ProjectDirs.html#method.data_local_dir) from the [`directories`](https://crates.io/crates/directories) crate).
Also, for consistency with this new env var, I renamed the field `Brioche.home` to `Brioche.data_dir` throughout the codebase. I thought this was more sensible since it's not really a "home directory" in any meaningful sense, and "data dir" is more consistent with the [XDG Base Directories …

Use `$BRIOCHE_DATA_DIR` to set directory for Brioche files

---

crates/brioche-core/src/cache.rs

This PR is a followup to #179 to enable conditional PUTs using ETags when using S3 as a backend for the cache. Previously, no option was set for conditional PUTs. Because we always use `PutMode::Create` when creating new objects through `object_store`, this meant that all cache writes for S3 would fail.
`object_store` doesn't enable this option by default because not all S3 backends have historically supported using ETags for conditional PUTs-- the most notable being actual Amazon S3. As of August 2024, Amazon S3 supports conditional PUTs now, and at least R2 does as well, so I think it should be fairly sensible to enable it by default. In the future, it might make sense to add an option to disable conditional PUTs for the cache, in case there are S3-compatible providers that don't …

Enable conditional PUTs for S3 object store

---

crates/brioche-core/src/cache.rs
crates/brioche-core/src/config.rs
crates/brioche-core/src/lib.rs

This PR is a follow-up to #179. As noted in the "Future improvements" section from that PR, `object_store` defaults to preventing requests to HTTP-based servers (in other words, it only allows HTTPS). The new `cache.allow_http` option and `$BRIOCHE_CACHE_ALLOW_HTTP` environment variable allow for optionally allowing HTTP requests.
I considered allowing this by default, or based on the URL scheme / S3 endpoint or similar, but decided to require explicit opt-in for now. I've definitely typo'd `https://` URLs as `http://` before, so I feel that trying to catch that is worth the trade-off.

Add `cache.allow_http` config setting to allow HTTP-only cache requests

---

crates/brioche-core/src/reporter/console.rs

This PR is a follow-up to #179, which tweaks how `CacheFetch` jobs are displayed when using the `--display plain` format for output. The messages are more detailed and more consistent with what the console output format shows.
Here's an example of the output you'd get when running `brioche build -r python` with this PR:
```
Fetching project from cache
Finished fetching project with 130 new blobs from cache in 0.05s
Fetching artifact from cache
Finished fetching artifact with 1 new blob from cache in 0.00s
Fetching artifact from cache
Finished fetching artifact with 1 new blob from cache in 0.00s
Fetching artifact from cache
Finished fetching artifact with 1 new blob from cache in 0.00s
Fetching artifact from cache
Finished fetching artifact with 6568 new blobs from cache in 13.02s
Build …
```

Tweak how cache fetch jobs are displayed in plain display format

---

Cargo.toml
crates/brioche-core/src/encoding.rs
crates/brioche-core/src/object_store_utils.rs
crates/brioche-core/src/output.rs
crates/brioche-core/src/process_events/display.rs
crates/brioche-core/src/project.rs
crates/brioche-core/src/project/artifact.rs
crates/brioche-core/src/reporter/console.rs
crates/brioche-core/src/script/specifier.rs
crates/brioche-core/src/sync/legacy_sync.rs
crates/brioche-core/src/sync/new_sync.rs
crates/brioche-core/tests/bake_process.rs
crates/brioche-core/tests/cache_client.rs
crates/brioche-core/tests/output.rs
crates/brioche/src/build.rs
crates/brioche/src/check.rs
crates/brioche/src/format.rs
crates/brioche/src/install.rs
crates/brioche/src/jobs/logs.rs
crates/brioche/src/main.rs
crates/brioche/src/migrate_registry_to_cache.rs
crates/brioche/src/run.rs
crates/brioche/src/run_sandbox.rs
crates/brioche/src/self_update.rs

This PR fixes some debug `println!()` statements that slipped through #179. I was running into issues with the LSP erroring out do to these (since the LSP uses a special protocol over stdio, and random `println!()` statements interfere with this).
Additionally, I enabled the Clippy lints [`print_stdout`](https://rust-lang.github.io/rust-clippy/master/index.html#print_stdout) and [`print_stderr`](https://rust-lang.github.io/rust-clippy/master/index.html#print_stderr) to catch more cases like this. There are a lot of places where we still use `println!()` intentionally for output, so I added `#[expect]` attributes as appropriate. Over time, I'm hoping more and more of these will move to use either `tracing` or our reporter machinery, so this will also help us audit once we (hopefully) move …

Fix debug printing and enable some more Clippy lints

---

Cargo.lock
crates/brioche-core/runtime/src/compat/console.ts
crates/brioche-core/runtime/src/compat/setup.cjs
crates/brioche-core/runtime/src/lsp.ts
crates/brioche-core/src/project.rs
crates/brioche-core/src/script/compiler_host.rs
crates/brioche-core/src/script/lsp.rs
crates/brioche-core/tests/lsp_basic.rs
crates/brioche-core/tests/lsp_completions.rs
crates/brioche-core/tests/lsp_on_save.rs
crates/brioche-test-support/Cargo.toml
crates/brioche-test-support/src/lib.rs
crates/brioche/src/lsp.rs

Fixes #186
This PR includes various bugfixes from the LSP. This originally stemmed from the regressions mentioned in #186, but I decided to tackle this issue by writing some integration tests for the LSP and kept running into various other (longstanding) bugs too.
So, there are a number of integration tests for the LSP now. It's not super comprehensive (mostly covering completions and handling the `didSave` notification), but I feel it's a good start.
Here's an overview of the bugs fixed in this PR:
- Fix regression where LSP would always try to download dependencies from the cache (and fail) during normal LSP requests (`didChange`, `completions`, etc.). Now, dependencies are only fetched if not already saved locally, and remote cache access is only enabled when handling the `didSave` …

Fix miscellaneous bugs in LSP

---

crates/brioche-core/src/project.rs
crates/brioche-core/tests/lsp_on_save.rs

This PR tweaks how lockfiles are updated when handling the `didSave` LSP event.
When the LSP client sends a `didSave` event, the LSP server will fetch dependencies and update the lockfile. If there's an existing lockfile, the current behavior is to completely override the `dependencies` section of the lockfile, leaving the `downloads` and `git_refs` sections in tact (since the LSP only fetches project dependencies, not statics).
Say you commented out a line like `import nodejs from "nodejs";` then hit save. The LSP would update the lockfile and remove the currently locked version of the `nodejs` dependency. Then, if you were to uncomment the line and hit save again, the LSP would fetch the latest version of `nodejs` and commit it to the lockfile, potentially locking to a new version …

Tweak LSP to keep unused dependencies when saving

---

.github/dependabot.yml

This PR tweaks the Dependabot config so Dependabot doesn't try to update any of our Biome dependencies. Biome's published Cargo packages don't seem to follow the general semver semantics used by most packages on https://crates.io (i.e. Biome has had breaking changes going from `0.x.y` to `0.x.z`), so it doesn't seem like we'll be able to smoothly use Dependabot to manage updates for them. See #184 for more context.

Tweak Dependabot config to ignore `biome` package updates

---

crates/brioche-core/src/project/analyze.rs
crates/brioche-core/tests/script_project_analyze.rs

This PR updates the project analysis to support converting several more types of constant JS expressions to JSON values, which lets these expressions be used for [statics](https://brioche.dev/docs/core-concepts/projects/#statics).
In this case, these are all fairly "boring" types of expressions (`as` casts, `satisfies`, etc.), but it can be convenient e.g. to use `satisfies` to validate the `project` export. Also, each of these expressions were marked with `todo!()`s already, I think I previously just forgot to implement them...

Support using more expressions when evaluating statics in project analysis

---

crates/brioche-core/src/cache/archive.rs
crates/brioche-core/tests/cache_client.rs

This PR fixes a bug introduced with the new cache in #179, where an archive in the cache containing an empty blob could sometimes fail to be read, resulting in the following error:
```
internal error: entered unreachable code: needed blobs are out of order
```
This recently caused a build failure in Brioche Packages in [CI #597](https://github.com/brioche-dev/brioche-packages/actions/runs/13560586298/job/37903036788) (commit https://github.com/brioche-dev/brioche-packages/commit/2b5e48222806ba6a7ebe3e0902e013800b48aae1, failed while building `packages/amber`)
The failure wasn't always consistent because (1) the contents of the archive had to be small enough that it fit inline within the archive (meaning the total size of all blobs had to be less than 2 MB), and (2) the blob had to come …

Fix occasional error when an inline cache archive contains an empty blob

---

.github/dependabot.yml
.github/workflows/ci.yml
crates/brioche-core/src/bake/process.rs

This PR is a minimal update to the "CI" GitHub Actions workflow and to the Dependabot config:
- Fix Dependabot exclusions introduced in #193 (the previous config excluded `biome` dependencies from the grouped Dependabot PR, which led to separate PRs for each `biome` update... the change here should actually ignore these dependencies now)
- Switch to the new `ubuntu-22.04-arm` GitHub Actions runner type when running aarch64 Brioche builds
- ~~Run tests in CI for Linux on both aarch64 and x86-64~~
- Removed due to test failures in `bake_process` tests, see: https://github.com/brioche-dev/brioche/actions/runs/13611821322/job/38049997140
- Clean up GH Actions job labels
- Add a new "All tests passed" job to the GH Actions workflow-- this can be used to simplify how PR requirements are …

Update Dependabot and switch to ARM64 for aarch64 builds

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/tests/object_store_utils_s3.rs
crates/brioche-test-support/Cargo.toml
crates/brioche-test-support/src/lib.rs

The [`tempdir`](https://github.com/rust-lang-deprecated/tempdir) crate had been deprecated long ago and no longer receives updates. The same functionality now exists in the `tempfile` crate.

Replace `tempdir` dependency with `tempfile`

---

Cargo.toml

See https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions

chore: remove resolver setting from Cargo.toml since this is the default value for Rust 1.85

---

Cargo.toml

Reverts brioche-dev/brioche#206
For some reason, this change broke the `brioche build` invocation (my guess is due to `cargo-chef`? But haven't dug into it)
Also, with the change from #206, I started getting this warning by default:
```
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2024 which implies `resolver = "3"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2024 resolver, specify `workspace.resolver = "3"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
```
Together, I think it makes sense to roll back and specify the resolve even though it's strictly …

Revert "chore: remove resolver setting from Cargo.toml since this is the default value for Rust 1.85"

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/cache.rs
crates/brioche-pack/Cargo.toml
crates/brioche-test-support/Cargo.toml
crates/brioche/Cargo.toml

This PR upgrades all of Brioche's Cargo dependencies. I ran `cargo upgrade`, `cargo upgrade --incompatible`, and `cargo update`. I got a weird error from the `cargo upgrade --incompatible` call, but I believe this caught everything (this should supersede #212)
I also switched from our fork of `object_store` (from [brioche-dev/arrow-rs](https://github.com/brioche-dev/arrow-rs/tree/object-store-disable-all-compression-formats/object_store), [permalink](https://github.com/brioche-dev/arrow-rs/tree/58f91d6b71bdc61f82e5f12226998d5994d25908/object_store)) to the latest upstream release of v0.12.0. There didn't seem to be any required code changes, but I did remove a call to `AmazonS3Builder.with_conditional_put()` that was made redundant.

Upgrade Cargo dependencies

---

crates/brioche-core/src/bake.rs
crates/brioche-core/src/bake/process.rs
crates/brioche/src/jobs.rs
crates/brioche/src/jobs/debug_shell.rs
crates/brioche/src/jobs/logs.rs

This PR adds a new `brioche jobs debug-shell` command. It takes a path to an `events.bin.zst` file (just like `brioche jobs logs`), then launches an interactive shell within the context of the job.
When the `events.bin.zst` format was added for process jobs in #138, one of the events that was added was the [`ProcessEventDescription`](https://github.com/brioche-dev/brioche/blob/469d224be6c36dafdad1607b5e7ff45c704dda04/crates/brioche-core/src/process_events.rs#L102) event, which includes a lot of context about how the process was run. It includes a full serialized version of the `SandboxExecutionConfig` used when we ran the process! So, launching a debug shell is fairly easy: this PR reads the `SandboxExecutionConfig` value from `events.bin.zst`, modifies it so it runs `/bin/sh -i` instead …

Add new command to start a debug shell within a job

---

crates/brioche-core/src/project/analyze.rs
crates/brioche-core/src/script.rs
crates/brioche-core/src/script/bridge.rs
crates/brioche-core/tests/script_eval.rs

This PR updates project analysis to parse `Brioche.gitCheckout` as a static.
From an implementation perspective, `Brioche.gitCheckout` is treated identically to [`Brioche.gitRef`](https://brioche.dev/docs/core-concepts/statics/#briochegitref). The main motivation behind this new method is to update the `brioche-packages` repo to provide a different implementation for `Brioche.gitCheckout`-- specifically, the new `Brioche.gitCheckout` function is intended to be implemented by checking out the returned git commit.
To help improve errors, I also tweaked the underlying `Deno.core.ops.op_brioche_get_static` function to accept a `callee` property in its options. The implementation should pass the function name, which will allow the Rust implementation to return a more specific error message.

Add support for `Brioche.gitCheckout` as a static

---

crates/brioche-core/runtime/build.ts
crates/brioche-core/runtime/package-lock.json
crates/brioche-core/runtime/package.json

This PR updates various dependencies under the NPM project `crates/brioche-core/runtime`. I also manually ran this command to re-generate the `dist/` directory under the project:
```sh
brioche build -e runtime -o crates/brioche-core/runtime/dist --replace
```
I kept the updates limited to only "internal" dependencies, so this shouldn't lead to any user-facing changes (hopefully). Most notably, TypeScript and ESLint have _not_ been updated.

Upgrade dependencies in `runtime` NPM project

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-core/src/bake/unarchive.rs
crates/brioche-core/src/cache/archive.rs
crates/brioche-core/src/download.rs
crates/brioche-core/src/process_events/reader.rs
crates/brioche-core/src/reporter/console.rs
crates/brioche-core/src/reporter/job.rs
crates/brioche-core/src/utils/io.rs

This PR tweaks how several jobs are displayed, both for the "pretty" console display and the plaintext display.
When the "cache" and "download" jobs run, they will show the size of downloaded data out of the total size. The "unarchive" job will show the number of bytes read from the archive out of the archive's total size. Sizes are shown using the [`bytesize`](https://docs.rs/bytesize/latest/bytesize/) crate.

Update console output to show download / archive sizes

---

crates/brioche-core/src/cache.rs
crates/brioche-core/src/config.rs
crates/brioche-core/src/lib.rs
crates/brioche-core/src/object_store_utils.rs

#179 introduced the new cache mechanism. That PR included support for configuring a custom cache using either the `cache.url` field in the Brioche config file, or the `$BRIOCHE_CACHE_URL` env var. Either way, using a custom cache would **replace** the default cache.
This made it difficult to actually use a custom cache: starting from a new cache, every recipe would need to be built from scratch. Additionally, pulling projects from the registry would always fail since the cache is also used to retrieve project sources.
With this PR, configuring a custom cache now acts as an **overlay** on top of the default cache. Every cache access first checks the custom cache, then falls back to the default cache if not found. You can still completely opt-out of the default cache by setting …

Treat custom cache config as an overlay instead of replacing default cache

---

crates/brioche-core/src/bake/process.rs
crates/brioche-core/src/config.rs
crates/brioche-core/src/sandbox.rs
crates/brioche-core/src/sandbox/unsandboxed.rs

Closes #220
This PR adds a new sandbox backend called `unsandboxed`. As the name implies, this effectively disables sandboxing, allowing build steps to run directly on the host system.
When used, builds can trivially break the rules of hermeticity, as they can perform any kind of operations on the host system. For example, the `.unsafe({ networking })` setting has no effect when using the unsandboxed backend, as the underlying process always has standard network access.
So, this backend should only be used as a last resort, such as when user namespaces are blocked and when PRoot isn't a suitable choice (because the `ptrace` syscall is blocked, because a PRoot binary isn't available, or when the performance hit from PRoot is too high). On the other hand, this sandbox only uses …

Implement `unsandboxed` sandbox backend

---

crates/brioche-core/src/bake/process.rs
crates/brioche-core/src/recipe.rs
crates/brioche-core/src/references.rs
crates/brioche-core/src/sandbox.rs
crates/brioche-core/src/sandbox/linux_namespace.rs
crates/brioche-core/src/sandbox/unsandboxed.rs
crates/brioche-core/tests/bake_process.rs
crates/brioche-core/tests/process_events.rs
crates/brioche-core/tests/recipe_hash_stable.rs
crates/brioche-test-support/src/lib.rs

This PR updates the `process` (and `complete_process`) recipe types with a new optional field: `currentDir`. When set to a process template value, the spawned process will change to a different directory before running, rather than the default `$HOME/work` directory (a.k.a `std.workDir`). Also, setting `currentDir` to `std.workDir` is treated exactly equivalent to omitting `currentDir`, which is important for preserving stable recipe hashes before and after this PR.
Here's a minimal example (note: will need a change in the `std` package as well)
```typescript
// Returns a recipe containing `hello.txt`
export default function() {
return std.runBash`
echo hi > hello.txt
`
.outputScaffold(std.directory())
.currentDir(std.outputPath)
.toDirectory();
}
```
Here, `.currentDir(std.outputPath)` …

Add `currentDir` option to process recipes

---

Cargo.lock
crates/brioche-core/src/project.rs
crates/brioche-core/src/project/analyze.rs
crates/brioche-core/src/project/edit.rs
crates/brioche-core/src/vfs.rs
crates/brioche-core/tests/project_edit.rs
crates/brioche/Cargo.toml
crates/brioche/src/live_update.rs
crates/brioche/src/main.rs

Closes #165 
This PR implements the new command `brioche live-update`. It either updates the current project or takes a project path to update (`-p`), as well as a fairly standard assortment of flags like `--check`, `--locked`, etc.
When called, it builds and runs the `autoUpdate` export (as if running `brioche run -e autoUpdate`). Then, it captures the process's stdout and parses it as JSON. This value is treated as the new project export (`export const project = {...}`), so it updates the file `project.bri`, reformats it, then reloads the project and updates the lockfile.
So, this lets the `autoUpdate` function make changes to `project.bri` based on arbitrary external sources. Here's an example [from the `ripgrep` package](https://github.com/brioche-dev/brioche-packages/blob/642eca1f635d …

Add `brioche live-update` command to live-update/auto-update projects

---

crates/brioche/src/live_update.rs

- Follow-up to #234
- Companion PR to https://github.com/brioche-dev/brioche-packages/pull/385
This PR updates the `brioche live-update` subcommand introduced in #234 to use the export named `liveUpdate` instead of `autoUpdate`. Now that https://github.com/brioche-dev/brioche-packages/pull/385 is ready to merge, we should get this change in on the Brioche side before merging the change on the Brioche Packages side.

Update `live-update` subcommand to use `liveUpdate` export

---

Cargo.toml

This PR speeds up builds for the `dev` profile by a decent amount. I made a small logging change within `brioche-core`, and the time it took to rebuild just the change files when running a test (`cargo test --test project_edit`) went from around 18 seconds to around 7 seconds on my machine.
I've been frustrated for a while with how long it was taking tests to run, even for very minor changes. Before I went down this rabbit hole, it was taking around 2 minutes or so to re-run tests, which just killed my momentum for larger features! Like I mentioned, the changes from this PR cut the time down from around 18 seconds down to 7-- I also made some changes to my local dev environment that accounted for the rest of the speedup. I'll outline the changes in this PR, the change I made locally, and …

Speed up debug compilation

---

brioche.lock

This PR upgrades the dependencies in `brioche.lock` to fix building Brioche with Brioche itself (the Rust version in `brioche.lock` was locked to v1.86, but project now requires v1.87)

Upgrade Rust version for Brioche-in-Brioche

---

.github/workflows/ci.yml

Follow-up for #249 to fix CI build failure (i.e. [CI #638](https://github.com/brioche-dev/brioche/actions/runs/15234413454))
This was a bug that was fixed by #216, which hasn't made it into a stable release yet. The CI pipeline uses Brioche v0.1.5 currently, so I felt the best option was to just add a ~~quick-and-dirty hack~~ workaround to get CI working for now

Add workaround for "file exists" bug in CI

---

crates/brioche-core/src/project.rs
crates/brioche-core/src/script/check.rs
crates/brioche-core/tests/script_check.rs
crates/brioche/src/build.rs
crates/brioche/src/check.rs
crates/brioche/src/format.rs
crates/brioche/src/install.rs
crates/brioche/src/live_update.rs
crates/brioche/src/main.rs
crates/brioche/src/publish.rs
crates/brioche/src/run.rs

This PR updates how the `brioche check` subcommand handles multiple projects. Rather than building a new `Projects` instance, loading each project, then checking each one in isolation, it instead checks all the modules from all the projects in one pass.
This should save a ton of time when checking the `brioche-packages` repo. Since every* package depends on `std`, the modules in `std` effectively get typechecked and linted every time. Early on, this wasn't a big problem-- but with ~150 packages, the CI time spent just checking is definitely noticeable!
Testing locally, here's a bash one-liner to check every package:
```sh
echo ./packages/* | xargs printf -- '-p %s\n' | xargs brioche check
```
- Before this change, this took **6m 1s**
- After this change, this took **7.5s**

Update `check` subcommand to check all projects in one pass

---

Cargo.toml
brioche.lock
crates/brioche-core/src/download.rs
project.bri
rust-toolchain.toml

This PR updates the Rust version in `rust-toolchain.toml`, `Cargo.toml`, and `project.bri` to use Rust v1.88.0.
There was a new warning that appeared that I fixed. I also made a few miscellaneous tweaks to the Brioche-in-Brioche build:
- Replace custom `sqlx-cli` build with upstream `sqlx_cli` package (https://github.com/brioche-dev/brioche-packages/pull/719)
- Update "validation" steps to run in parallel

Update to Rust v1.88

---

crates/brioche-core/src/project/load.rs

I was going to update Rust to 1.88, too. But [you were faster](https://github.com/brioche-dev/brioche/pull/267) than me. So, I merged your changes with mine locally, and here is the diff.

refactor: make use of the new if let chains pattern with Rust 1.88

---

.github/dependabot.yml
.github/workflows/ci.yml

This PR makes minor updates to CI configuration files by using the [YAML Language Server](https://github.com/redhat-developer/yaml-language-server) to format the files and by ungrouping GitHub Actions updates if more than once are updated at the same time by Dependabot (which shouldn't be too common).
By default the YAML LSP format the strings with double quotes, there is a setting to use single quote. But I'm assuming that we should stay to the default settings, plus we are sometimes using double quote strings in this repository.

Update GitHub CI files

---

.github/workflows/ci.yml

This PR updates the CI workflow configuration to support building artifacts for aarch64 platform. This is a follow up of the ongoing support of Brioche on aarch64 operating system.

ci(brioche): build aarch64 packed artifacts

---

.github/workflows/ci.yml

This PR fixes the CI build for the packed aarch64 artifact, which was always running using a runner type of `ubuntu-24.04`. Since the build itself isn't cross-compiling, this meant the final binary ended up being built for x86-64 rather than aarch64

Fix CI build for packed aarch64 artifact using x86-64

---

.github/workflows/ci.yml

Follow-up to #292 
The build after merging #292 still failed, but this time because the CI job was still using the `brioche-dev/setup-brioche` action, which doesn't work for aarch64 currently (since the last stable release of Brioche didn't include aarch64 support yet).
This PR works around it by using the nightly version of Brioche, just like the `brioche-packages` repo currently does: https://github.com/brioche-dev/brioche-packages/blob/811a87dcd6c420ba0d6da314cb512849637a6036/.github/workflows/_build.yml#L33-L40 (but here we still use the stable version for x86-64)

Use Brioche nightly for building packed aarch64 build

---

crates/brioche-core/src/lazy_bake.rs
crates/brioche-core/src/lib.rs
crates/brioche-core/tests/lazy_bake.rs
crates/brioche/src/build.rs

Some background context: [`brioche-packages`](https://github.com/brioche-dev/brioche-packages) has a lot of packages now! Meanwhile, all the builds run on our self-hosted runners (currently: a mini PC and a Mac mini sitting in the garage). So we're definitely starting to feel the inefficiencies in our build pipeline!
The basic CI pipeline works like this:
1. Check all packages (sped up greatly by #255)
2. Run `brioche build --sync` for each package, one by one
3. Run `brioche build -e test --sync` for each package, one by one
4. Run `brioche publish` for each package, one by one
Currently, `brioche build` will always ensure the build result is available locally, by either baking each recipe or fetching its result from the remote cache. But for the `brioche-packages` CI pipeline, we never …

Add new `--experimental-lazy` CLI option for `brioche build`

---

crates/brioche-core/Cargo.toml
crates/brioche-core/src/reporter/console.rs

I was trying out Grafana for showing Brioche's OpenTelemetry traces today, and I found out that enabling the OpenTelemetry output (setting `BRIOCHE_ENABLE_OTEL=1` and `OTEL_EXPORTER_OTLP_ENDPOINT`) was causing a panic:
```
thread 'OpenTelemetry.Traces.BatchProcessor' panicked at $HOME/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hyper-util-0.1.15/src/client/legacy/connect/dns.rs:119:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I found out that this related to how we constructed the OTLP HTTP client (we were using the async client, but `opentelemetry-otlp` started expecting the blocking client at some point I think). I tried explicitly passing …

Fix panic when enabling OpenTelemetry output

---

.github/workflows/ci.yml

In https://github.com/brioche-dev/brioche-packages and https://github.com/brioche-dev/setup-brioche, we are already using this terminology. So this PR is just here to uniformize syntaxes across repositories.

ci: update workflow to use runs-on instead of runs_on

---

.github/workflows/ci.yml

Using `include` as the name for defining multiple scenarios in a matrix can help t reduce the boilerplate when referring to a variable of the scenario (see https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations#expanding-or-adding-matrix-configurations). It's true for only `include` name.
If this PR is okay to merge as is, I'll open two additional PRs in other repos of Brioche.

ci: update workflow to use matrix include syntax

---

Cargo.lock
crates/brioche-core/Cargo.toml
crates/brioche-test-support/Cargo.toml
crates/brioche/Cargo.toml

We don't need anymore to pin the `object_store` decency, since a new release has been done recently and it includes the work of this [PR](https://github.com/apache/arrow-rs-object-store/pull/441).

build: update object_store to version 0.12.4
